/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bool.plugin.adventures

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class BoolPluginAdventuresKotlinPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.extensions.create("kotlin", KotlinExtension::class.java)
    }
}
