/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bool.plugin.adventures

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'bool.plugin.adventures.greeting' plugin.
 */
class BoolPluginAdventuresKotlinPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("bool.plugin.adventures.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
