/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bool.plugin.adventures;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class BoolPluginAdventuresPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getExtensions().create("java", JavaExtension.class);
    }
}
