/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package bool.plugin.adventures

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'bool.plugin.adventures.greeting' plugin.
 */
class BoolPluginAdventuresGroovyPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("bool.plugin.adventures.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
